version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis_n8n
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  n8n:
    image: n8n/n8n:latest
    container_name: n8n
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "5678:5678"
    environment:
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: "${N8N_BASIC_AUTH_USER}"
      N8N_BASIC_AUTH_PASSWORD: "${N8N_BASIC_AUTH_PASSWORD}"
      GENERIC_TIMEZONE: "America/Sao_Paulo"
      N8N_REDIS_URL: "redis://redis:6379"
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  redis_data:
  n8n_data:
