version: "3.9"
services:
  kelly:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS:-/secrets/sa.json}
    volumes:
      - ./service-account.json:/secrets/sa.json:ro
    restart: unless-stopped
